sudo: required
language: ruby
env: RACK_ENV=development
before_script:
- git clone https://github.com/pepita-remembrance/cspec.git && cd cspec && make && sudo make install && cd ..
rvm:
 - 2.0.0
services:
  - docker
before_install:
- docker pull mumuki/mumuki-cspec-worker